version: "3"
services:
  frontend:
    image: pizza-front:0.1
    build: ../frontend
    depends_on:
      - backend
      - database
    networks:
      - frontend
    ports:
      - "8888:8888"
  backend:
    image: pizza-back:0.7
    build: ../backend
    depends_on:
      - database
    networks:
      - frontend
      - backend
  database:
    image: postgres:14
    command: -c 'max_connections=1000'
    environment:
      POSTGRES_DB: "pizza"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    expose:
      - 5432
    networks:
      - backend

networks:
  frontend:
  backend: