server {
    listen       8888;
    server_name  frontend;

    location / {
        root   /app;
        index  index.html;
    }

    location /docs {
        proxy_pass http://backend/docs;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

upstream backend {
   server backend:3000;
}

